name: second
on: [push]

jobs: 
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Testing checkout
        uses: actions/checkout@v4
      - name: Dir
        run: |
          pwd
          ls -la